name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, clippy
    - name: Build
      run: |
        cargo build --verbose
    - name: Check format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
